---
- hosts: local
  tasks:
    # - name: Ansible Setup
    #   include: tasks/ansible-setup.yml
    - name: Set Preferences
      include: tasks/preferences.yml
    - name: Configure Dock
      include: tasks/dock.yml
    - name: OS X Setup
      script: scripts/setup_osx


  roles:
    - homebrew
    - dotfiles
