---
- hosts: local
  become: yes
  become_method: sudo
  roles:
    - homebrew

- hosts: local
  roles:
    - osx_config
    - dotfiles

- hosts: local
  tasks:
    - name: Set Preferences
      include: tasks/preferences.yml
    - name: Configure Dock
      include: tasks/dock.yml
