---
- name: Configure Bash Profile
  become: no
  copy: src=./files/{{ item }} dest=~ mode=755
  with_items:
    - .bash_profile
    - .bashrc
    - .gitignore
    - .vimrc
- name: Configure GIT
  become: no
  template: src=.gitconfig.j2 dest=~/.gitconfig mode=755
