---
- name: Menu bar - disable transparency
  command: defaults write NSGlobalDomain AppleEnableMenuBarTransparency -bool "{{ menu_bar_transparency }}"

- name: Menu bar - show remaining battery time (on pre-10.8)
  command: defaults write com.apple.menuextra.battery ShowPercent -string "NO"
  when: "{{ show_remaining_battery }}"

- name: Menu bar - show remaining battery - hide percentage
  command: defaults write com.apple.menuextra.battery ShowTime -string "YES"
  when: "{{ show_remaining_battery }}"

- name: Set highlight color to green
  command: defaults write NSGlobalDomain AppleHighlightColor -string "0.764700 0.976500 0.568600"
  when: "{{ highlight_color_green }}"

- name: Expand save panel by default
  command: defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool "{{ expand_save_panel }}"

- name: Expand print panel by default
  command: defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool "{{ expand_print_panel }}"

- name: Save to disk - not to iCloud by default
  command: defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool "{{ save_new_documents_on_cloud }}"

- name: Disable the - Are you sure you want to open this application - dialog
  command: defaults write com.apple.LaunchServices LSQuarantine -bool "{{ lsquarantine }}"

- name: Reveal IP address, hostname, OS version, when clicking the clock in loginwindow
  command: defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName
  when: "{{ reveal_info_on_login }}"

- name: Check for software updates daily, not just once per week
  command: defaults write com.apple.SoftwareUpdate ScheduleFrequency -int "{{ software_update_frequency }}"

- name: Restart automatically if the computer freezes
  command: systemsetup -setrestartfreeze on
  when: "{{ auto_reboot_on_freez }}"

- name: Set a blazingly fast keyboard repeat rate
  command:  defaults write NSGlobalDomain KeyRepeat -int 0
  when: "{{ fast_keyboard }}"

- name: Set auto correct
  command: defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool "{{ auto_correct }}"

- name: Create screenshot directory
  file: path=/src/www"{{ screenshot_directory }}" state=directory

- name: Save screenshots directory
  command: defaults write com.apple.screencapture location -string "{{ screenshot_directory }}"

- name: Set screenshots format
  command: defaults write com.apple.screencapture type -string "{{ screenshot_format }}"

- name: Set show | hide hidden files
  command: defaults write com.apple.finder AppleShowAllFiles -bool "{{ show_hidden_files }}"

- name: Set show | hide all filename extensions
  command: defaults write NSGlobalDomain AppleShowAllExtensions -bool "{{ show_files_extensions }}"

- name: Set show | hide full POSIX path as Finder window title
  command: defaults write com.apple.finder _FXShowPosixPathInTitle -bool "{{ show_posix_path_in_finder_title }}"

- name: Set show | hide warning when changing a file extension
  command: defaults write com.apple.finder FXEnableExtensionChangeWarning -bool "{{ extension_change_warning }}"

- name: Avoid creating .DS_Store files on network volumes
  command: defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

- name: Automatically open a new Finder window when a volume is mounted - RO
  command: defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool "{{ open_finder_volume_on_mount }}"

- name: Automatically open a new Finder window when a volume is mounted - RW
  command: defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool "{{ open_finder_volume_on_mount }}"

- name: Automatically open a new Finder window when a volume is mounted - NET
  command: defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool "{{ open_finder_volume_on_mount }}"

- name: Use list view in all Finder windows by default    # modes: `icnv`, `clmv`, `Flwv`
  command: defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

- name: Set show | hide warning before emptying the Trash
  command: defaults write com.apple.finder WarnOnEmptyTrash -bool "{{ warn_on_empty_trash }}"

- name: Set empty Trash securely
  command: defaults write com.apple.finder EmptyTrashSecurely -bool "{{ empty_trash_securely }}"

- name: Enable spring loading for all Dock items
  command: defaults write com.apple.dock enable-spring-load-actions-on-all-items -bool true

- name: Show indicator lights for open applications in the Dock
  command: defaults write com.apple.dock show-process-indicators -bool true

- name:  Disable animate opening applications from the Dock
  command: defaults write com.apple.dock launchanim -bool true

- name: Set dock tile size
  command: defaults write com.apple.dock tilesize -int "{{ dock_tile_size }}"

- name: Set dock large size
  command: defaults write com.apple.dock largesize -int "{{ dock_largesize_size }}"

- name: autohide dock
  command: defaults write com.apple.dock autohide -bool "{{ autohide_dock }}"

- name: remove dock delay
  command: defaults write com.apple.dock autohide-delay -float 0
  when: "{{ autohide_dock }}"

- name: Speed up Mission Control animations
  command: defaults write com.apple.dock expose-animation-duration -float 0.1

- name: Set group windows by application in Mission Control
  command: defaults write com.apple.dock expose-group-by-app -bool "{{ group_windows_by_application }}"

- name: Disable local Time Machine backups - hash tmutil
  command: hash tmutil
- name: Disable local Time Machine backups - tmutil disablelocal
  command: tmutil disablelocal

- name: Allow text selection in the Quick Look window
  command: defaults write com.apple.finder QLEnableTextSelection -bool true

- name: Disable the sudden motion sensor as not useful for SSDs
  command: pmset -a sms 0

- name: Disable the crash reporter
  command: defaults write com.apple.CrashReporter DialogType -string "none"

- name: Require password after screen saver
  command: defaults write com.apple.screensaver askForPassword -int 1
- name: Require password immediately after sleep or screen saver
  command: defaults write com.apple.screensaver askForPasswordDelay -int 0

- name: Disable useless dashboard
  command: defaults write com.apple.dashboard mcx-disabled -boolean YES

- name: Reload Dock
  command: killall Dock
